export interface COLOR {
  colorName: string
  colorCode: string
}

export const getDefaultColors = () => {
  const colorName = [
    'Black',
    'Blue',
    'Brown',
    'White',
    'Beige',
    'Pink',
    'Purple',
    'Navy',
    'Orange',
    'Gray/Grey',
    'Green',
    'Yellow',
    'Khaki',
    'Yellow Leopard',
    'All Black/Whole Black',
    'Black Gray',
    'Black White',
    'Red',
    'Wine Red',
    'Coffee',
    'Light Blue ',
    'Yellow Green',
    'Orange Yellow',
    'Red Green',
    'Dark Grey',
    'Gold',
    'Silver',
    'Leopard',
    'Bronze',
    'Dark Blue',
    'Rose Red',
    'Chocolate Leopard',
    'Snakeskin Pattern',
    'Zebra Pattern ',
    'Baby Pink',
    'Transparent/Clear',
    'Light Grey',
    'Navy Red',
    'Navy',
    'Blue',
    'Brown Green',
    'Army Green',
    'Apricot',
    'Peach',
    'Glinting Silver',
    'Grey Silver',
    'Champagne',
    'Pink Crystal',
    'White Crystal',
    'Black Crystal',
    'White Leopard',
    'Charcoal ',
    'Multi-Color',
    'Dark Green',
    'Coral',
    'Light Purple',
    'Floral',
    'Dark Purple',
    'Dark Brown',
    'Rose Gold',
  ]
  const colorCode = [
    'BK',
    'BL',
    'BR',
    'WH',
    'BE',
    'PK',
    'PP',
    'NV',
    'OR',
    'GY',
    'GR',
    'YL',
    'KI',
    'YLLP',
    'ABK',
    'BKGY',
    'BKWH',
    'RD',
    'WRD',
    'CF',
    'LBL',
    'YLGR',
    'ORYL',
    'RDGR',
    'DGY',
    'GD',
    'SV',
    'LP',
    'BZ',
    'DBL',
    'RRD',
    'CCLLP',
    'SP',
    'ZP',
    'BPK',
    'TM',
    'LGY',
    'NVRD',
    'NVBL',
    'BRGR',
    'AYGR',
    'AP',
    'PH',
    'GLSV',
    'GYSV',
    'CP',
    'PC',
    'WC',
    'BC',
    'WHLP',
    'CC',
    'MCL',
    'DGR',
    'CL',
    'LPP',
    'FL',
    'DPP',
    'DBR',
    'RGD',
  ]

  const result: COLOR[] = []
  for (let i = 0; i < colorName.length; i++) {
    result.push({
      colorName: colorName[i],
      colorCode: colorCode[i],
    })
  }
  return result
}
